const glasses = {
  AbsintheGlass: 'Tall narrow glass traditionally used for absinthe',
  BrandySnifterGlass: 'Short, wide bowl for brandy and aromatics',
  CollinsGlass: 'Tall, slim highball-style glass for long drinks',
  CopperMug: 'Insulated mug commonly used for Moscow Mules',
  CordialGlass: 'Small stemmed glass for cordials and liqueurs',
  CoupeGlass: 'Shallow, broad-bowled stemmed glass for cocktails',
  DemitasseGlass: 'Tiny cup used for espresso or small servings',
  DoubleShotGlass: 'Small glass sized for a double shot or liqueur',
  FizzGlass: 'Tall glass for fizzy, highball-like cocktails',
  FluteGlass: 'Narrow stemmed glass for sparkling cocktails or champagne',
  GobletGlass: 'Large bowl stemmed glass for water or wine-style serves',
  HighballGlass: 'Tall glass for mixed drinks over ice',
  HurricaneGlass: 'Curved glass used for tropical, rum-forward drinks',
  IrishCoffeeGlass: 'Handled glass for hot cocktails like Irish Coffee',
  JulepCup: 'Silver or metal cup for mint juleps served over crushed ice',
  MargaritaGlass: 'Broad-rimmed glass typically used for margaritas',
  MartiniGlass: 'Classic conical stemmed glass for martinis and cocktails',
  NickAndNoraGlass: 'Small stemmed cocktail glass named for film characters',
  ParfaitGlass: 'Tall, elegant glass for layered desserts or cocktails',
  PilsnerGlass: 'Tall tapered glass for pilsner-style beers',
  PintGlass: 'Standard pint glass for beer servings',
  PousseCafeGlass: 'Very tall, narrow glass for layered pousse-cafés',
  PunchGlass: 'Large bowl or glass used for punch servings',
  RocksGlass: 'Short, wide glass for spirits served over ice',
  SingleShotGlass: 'Small single-shot glass for neat pours',
  SlingGlass: 'Stemmed glass used historically for sling cocktails',
  SnifterGlass: 'Rounded glass for nosing spirits like brandy or cognac',
  SourGlass: 'Stemmed glass for sours and shaken cocktails',
  TankardGlass: 'Large handled mug, often used for beer',
  TikiGlass: 'Themed ceramic or glass mug for tiki-style cocktails',
  ToddyGlass: 'Handled mug for hot toddies and warm drinks',
  WhiskeyShotGlass: 'Small glass for whiskey shots',
  WineGlass: 'Standard stemmed glass for wine service',
};

export default glasses;
export { glasses };
